# Generated by Django 5.0.7 on 2024-07-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_rename_service_ion_service_service_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='billinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('month_frm', models.DateField()),
                ('month_to', models.DateField()),
                ('meter_id', models.IntegerField()),
                ('prev_read', models.IntegerField()),
                ('new_read', models.IntegerField()),
                ('units', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='paymentrecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('refid', models.CharField(max_length=12)),
                ('remark', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
