# Generated by Django 5.0.7 on 2024-08-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('meter_reading', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entry_date', models.DateField()),
                ('yyyymm', models.CharField(max_length=6)),
                ('units_delta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units_cumulative', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
