# Generated by Django 5.0.7 on 2024-08-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dashboard',
            new_name='Charts',
        ),
    ]
