# Generated by Django 5.0.7 on 2024-08-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_alter_charts_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charts',
            name='user',
        ),
        migrations.AddField(
            model_name='charts',
            name='user_id',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
